// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfPccGZJZK-3JQAZqgRJIZ6HrrSS5RZBA',
    appId: '1:682553889447:web:aa7867f971a340e2638182',
    messagingSenderId: '682553889447',
    projectId: 'firepushnotification-53c48',
    authDomain: 'firepushnotification-53c48.firebaseapp.com',
    storageBucket: 'firepushnotification-53c48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2FORLQBNwqYMhn60Kv_uzqEreLRTcY5o',
    appId: '1:682553889447:android:66ed0afb85cabc81638182',
    messagingSenderId: '682553889447',
    projectId: 'firepushnotification-53c48',
    storageBucket: 'firepushnotification-53c48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpasqdy1XJtsekWpIhwj0Jwi6xX6xYxLs',
    appId: '1:682553889447:ios:525fbadf0cd82e55638182',
    messagingSenderId: '682553889447',
    projectId: 'firepushnotification-53c48',
    storageBucket: 'firepushnotification-53c48.firebasestorage.app',
    iosBundleId: 'com.example.firebasepushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpasqdy1XJtsekWpIhwj0Jwi6xX6xYxLs',
    appId: '1:682553889447:ios:525fbadf0cd82e55638182',
    messagingSenderId: '682553889447',
    projectId: 'firepushnotification-53c48',
    storageBucket: 'firepushnotification-53c48.firebasestorage.app',
    iosBundleId: 'com.example.firebasepushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfPccGZJZK-3JQAZqgRJIZ6HrrSS5RZBA',
    appId: '1:682553889447:web:fc1ab4cf1b5928dd638182',
    messagingSenderId: '682553889447',
    projectId: 'firepushnotification-53c48',
    authDomain: 'firepushnotification-53c48.firebaseapp.com',
    storageBucket: 'firepushnotification-53c48.firebasestorage.app',
  );
}
